models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./foo:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --working-directory ./ --reload-on-changes ./foo/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
   ports:
      - "8002:8000"
   volumes:
      - ./exp:/app
   command: "mod_wsgi-express start-server --reload-on-changes ./exp/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./web:/app
   command: "mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"
